### ISSUE TITLE
Proposal for Deploying the WikiNearby Project.

### ISSUE THREAD

**Issue by Nickson-Simiyu** [BrandonXLF/WikiNearby#1]
Hi Brandon,

I’m interested in helping you deploy the Python project from this repository. Below are my answers to your questions:

Cheap or Free Hosting Provider
I recommend [Railway](https://railway.app/) or [Render](https://render.com/) for free or cost-effective hosting. Both are reliable for Python-based projects. Alternatively, AWS Free Tier or Heroku (limited free tier) can also work.

What Else Is Needed for Deployment
Environment variables (e.g., API keys or credentials).
Details on the query adjustments you’d like to configure.
Access to this repository to set up and deploy the project.
GitHub Profile for Private Sharing
You can share private repositories with me at Nickson-Simiyu.

Fixed Price to Deploy the Code
I propose a fixed price of $50 to deploy the code (including hosting setup and verification).

Something I Enjoy Besides Coding
Outside of coding, I enjoy watching anime.

Let me know if you’d like to proceed! I’m looking forward to working on this project. You can also view my full profile and work history on Upwork here: [Nickson Simiyu Upwork Profile](https://www.upwork.com/freelancers/~01a43ff2569bc8da7b?mp_source=share).

Best regards,
Nickson Simiyu

**Comment by banjaminlee** [comment]
https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work with you.
I look forward your reply.

**Comment by Nickson-Simiyu** [comment]
> https://bold.pro/my/banjamin-lee-241212153841
> 
> This is my resume. I want to work with you. I look forward your reply.

yeah sure anytime

**Comment by banjaminlee** [comment]
Do you want to make more money?

**Comment by Nickson-Simiyu** [comment]
> Do you want to make more money?

yeah any ideas?

**Comment by banjaminlee** [comment]
I checked ur upwork profile and I can make your profile shiny and make more money

**Comment by banjaminlee** [comment]
your opinion?

**Comment by Nickson-Simiyu** [comment]
> your opinion?

and?

**Comment by banjaminlee** [comment]
do you understand what I mean?

**Comment by banjaminlee** [comment]
Your earning is $25, right?

**Comment by Nickson-Simiyu** [comment]
> Your earning is $25, right?

yeah

**Comment by banjaminlee** [comment]
I can make more money than you

**Comment by Nickson-Simiyu** [comment]
> I can make more money than you

please get straight to the point?

**Comment by banjaminlee** [comment]
You need a PC.
And anydesk installed on your PC.
That is all

**Comment by banjaminlee** [comment]
Hi, are u there?
